export const defaultTheme = {
  colors: {
    brand: {
      yellowDark: '#C47F17',
      yellow: '#DBAC2C',
      yellowLight: '#F1E9C9',
      purpleDark: '#4B2995',
      purple: '#8047F8',
      purpleLight: '#EBE5F9',
      text: '#574F4D',
    },
    base: {
      yellowDark: '#C47F17',
      title: '#272221',
      subtitle: '#403937',
      text: '#574F4D',
      label: '#8D8686',
      hover: '#D7D5D5',
      button: '#E6E5E5',
      input: '#EDEDED',
      card: '#F3F2F2',
      background: '#FAFAFA',
      white: '#FFFFFF',
      error: '#FF0000',
    },
  },
  fontSizes: {
    xg: '48px',
    xxl: '32px',
    xl: '24px',
    lg: '20px',
    xmd: '18px',
    md: '16px',
    sm: '14px',
    xs: '12px',
    xxs: '10px',
  } as const,
  fontFamily: {
    regular: 'Roboto',
    title: "'Baloo 2'",
  },
  radius: {
    sm: '4px',
    md: '6px',
  },
} as const
